package example_test

import (
	"crypto/rand"
	"testing"

	"github.com/stretchr/testify/require"
)

// define a mock stream

func TestCreateBigFile(t *testing.T) {
	cases := map[string]struct {
		nBytes int64 // number of randomly-generated bytes to write
	}{
		"empty file": {
			nBytes: 0,
		},
		"4 KiB file": {
			nBytes: 4 * 1024 * 1024,
		},
		"4 MiB file": {
			nBytes: 4 * 1024 * 1024 * 1024,
		},
	}

	for name, c := range cases {
		t.Run(name, func(t *testing.T) {
			// generate random bytes
			randomBytes := make([]byte, c.nBytes)

			n, err := rand.Read(randomBytes)
			require.Nil(t, err)
			require.Equal(t, c.nBytes, n)

			// feed the random bytes into example.CreateBigFile

			// require.Nil(t, err)
			// require.Equal(t, randomBytes, mockStream.bytesWritten)
		})
	}
}

// define a mock stream

func TestGetBigFile(t *testing.T) {

}
